#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define ANCHO 20
#define ALTO 20

#define NOMBRE_JUEGO "TESORO BINARIO"

#define CANTIDAD_JUGADORES 2
#define CANTIDAD_TESOROS 4

#endif /* CONSTANTES_H_ */
